name: inventorio
description: Basic home inventory in Flutter

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^0.2.0
  uuid: ^0.5.3
  barcode_scan: ^0.0.4
  image_picker: ^0.4.0
  path_provider: ^0.4.0
  quiver_hashcode: ^1.0.0
  google_sign_in: ^3.0.1
  firebase_analytics: ^0.3.1
  firebase_auth: ^0.5.10
  cloud_firestore: ^0.7.1
  firebase_storage: ^0.3.5
  json_annotation: ^0.2.3
  connectivity: ^0.3.0
  transparent_image: ^0.1.0
  intl: ^0.15.6
  cached_network_image: ^0.4.1+1
  qr_flutter: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.8.9
  json_serializable: ^0.5.2
  flutter_launcher_icons: ^0.5.0

flutter_icons:
  android: true
  ios: true
  image_path: resources/icons/icon.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: resources/fonts/Raleway/Raleway-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: resources/fonts/Montserrat/Montserrat-Regular.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
